### ISSUE TITLE
Examples of prepositional phrases contradict rules given.

### ISSUE THREAD

**Issue by russsharek** [Ahemmetter/toki-pona#2]
'mi kepeken e poki'

According to rules given, kepeken does not require e for the direct object in this case.

As I understand it, jan Pije's syntax used that example with the e usage. According to pu it would be...

mi kepeken poki

Unless I misunderstand it entirely, which is possible.

**Comment by russsharek** [comment]
Useful discussion on the topic

https://x0r.be/@jansegers/99903473407305103

**Comment by Ahemmetter** [comment]
True. I changed the rule, because it seems _kepeken_ can stand both with and without _e_, depending on its context. Both types of sentences are included as examples: _I use a cup_ (where the cup is an object like in any other sentence), and _I am eating with a spoon_ (basically the spoon is in the prepositive case like in Slavic languages). So, it's probably best to treat _kepeken_ differently from the other prepositions.

**Comment by russsharek** [comment]
As I understand it from pu, kepeken (and all words like it) get no 'e' when used as a preposition and e when referring to a direct object.

On May 17, 2018 3:01:19 PM CDT, Ahemmetter <notifications@github.com> wrote:
>True. I changed the rule, because it seems _kepeken_ can stand both
>with and without _e_, depending on its context. Both types of sentences
>are included as examples: _I use a cup_ (where the cup is an object
>like in any other sentence), and _I am eating with a spoon_ (basically
>the spoon is in the prepositive case like in Slavic languages). So,
>it's probably best to treat _kepeken_ differently from the other
>prepositions.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Ahemmetter/toki-pona/issues/2#issuecomment-389991110

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Ahemmetter** [comment]
Yes, I understood it in the same way. So, I would say kepeken just can be both: a preposition (then it doesn't have e) or just a verb (then it needs an e to show the direct object). Do you think the change reflects this enough?

**Comment by russsharek** [comment]
My confusion is that all of the prepositions can be used in the same way. I think the important thing to work into the explanation is "preposition = no e" and "verb/etc = use e"

**Comment by Ahemmetter** [comment]
Ah! Your'e right, I missed that. I somehow thought it only applies to kepeken.
